INSERT INTO museums (name, location, description, image_url)
VALUES (
  'British Museum',
  'Great Russell Street, London, England',
  'The British Museum is a public museum dedicated to human history, art and culture located in the Bloomsbury area of London. Its permanent collection of eight million works is the largest in the world. It documents the story of human culture from its beginnings to the present. Established in 1753, the British Museum was the world''s first public national museum. In 2025, the museum received 6,440,120 visitors and was the second most visited attraction in the United Kingdom.

	At its beginning, the museum was largely based on the collections of the Anglo-Irish physician and scientist Sir Hans Sloane. It opened to the public in 1759, in Montagu House, on the site of the current building. The museum''s expansion over the following 250 years was largely a result of British colonisation and resulted in the creation of several branch institutions, or independent spin-offs, the first being the Natural History Museum in 1881. Some of its best-known acquisitions, such as the Greek Elgin Marbles and the Egyptian Rosetta Stone, are subject to long-term disputes and repatriation claims.

	In 1973, the British Library Act 1972 detached the library department from the British Museum, but it continued to host the now separated British Library in the same Reading Room and building as the museum until 1997. The museum is a non-departmental public body sponsored by the Department for Culture, Media and Sport. Like all UK national museums, it charges no admission fee except for loan exhibitions.",
  'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/British_Museum_%28aerial%29.jpg/330px-British_Museum_%28aerial%29.jpg,https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpixnio.com%2Ffree-images%2Farchitecture%2Fmuseums%2Ffront-entrance-to-the-british-museum-in-london-england.jpg&f=1&nofb=1&ipt=e5234e7f789a9f2b58acc67aa9d7d7fab7cb57d20d5db018e14ff2781e6b5ae4,https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic.euronews.com%2Farticles%2Fstories%2F08%2F89%2F96%2F72%2F1920x1080_cmsv2_c5d09350-00a3-5c36-802e-12106e8ebde4-8899672.jpg&f=1&nofb=1&ipt=f8a7103fba011fe606714102a03fc527fbfca9e3952bbfb2fdbee494f2e6c0ef,https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.glastroesch.com%2Ffileadmin%2Fuser_upload%2FNews%2F2022%2FBritish_Museum__London%2Fmuseum-458322.jpg&f=1&nofb=1&ipt=1b0292313337b380864b4dc77ae652bb422bda155b5f3aad8748cdb116cd7d82 '
);